import esbuild from 'esbuild';
import { builtinModules } from 'node:module';
import { promises as fs } from 'node:fs';
import process from 'node:process';

const production = process.argv[2] === 'production';
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
*/
`;

const injectedBuild = await esbuild.build({
	entryPoints: ['src/injected.ts'],
	bundle: true,
	platform: 'browser',
	format: 'iife',
	target: 'es2021',
	legalComments: 'eof',
	minify: production,
	write: false,
});

const injectedCode = injectedBuild.outputFiles?.[0]?.text;
if (!injectedCode) {
	throw new Error('esbuild did not produce the Dark Reader injector.');
}

await fs.writeFile(
	'src/generated-injector.ts',
	`// Generated by esbuild.config.mjs. Do not edit manually.\nexport const DARK_READER_INJECTOR = ${JSON.stringify(injectedCode)};\n`,
);

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: production ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: production,
});

if (production) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
